### ISSUE TITLE
Support mandatory fields in createChange

### ISSUE THREAD

**Issue by satwikabea** [jenkinsci/service-now-plugin#12]
The ServiceNow instance we use requires some fields when creating a change and it doesn't look like there is a way to send these variables using this plugin.
Are there plans to support these fields in the near future?

**Comment by jmcshane** [comment]
Thanks for your question @satwikabea. This project is targeted towards the standard change request workflow, this workflow requires first a POST to the `sn_sc` endpoint. This endpoint doesn't appear to take data to fill in the change for that POST. Can you try to just use the update item step to update the change request after it is created?

**Comment by satwikabea** [comment]
Our end user goal is to create a change and not update the existing one . We are creating a Standard change but are using some variables. These are not supported using the existing plug in .

**Comment by satwikabea** [comment]
Shane , just wanted to follow up on the above request ? Are there plans to support these fields in near future ?

**Comment by pdkreid** [comment]
@satwikabea 
The supported process here is to run 2 steps in order to get the results you are looking for:
1. Create the change using the currently available fields/values
2. Update the change with any additional custom fields/values you need.
