### ISSUE TITLE
How to use servicenow plugin in a Pipline

### ISSUE THREAD

**Issue by EhsanMirzaei** [jenkinsci/service-now-plugin#13]
Hi,

Can you please give an example of how this plugin can be used in a Jenkins pipeline? 
It's a bit unclear for me how to use this plugin.

Regards

**Comment by pdkreid** [comment]
@EhsanMirzaei There are examples of each of the plugin steps in the [README.md](https://github.com/jenkinsci/service-now-plugin/blob/master/README.md)
