### ISSUE TITLE
After plugin installation Servicenow option not found in "Configure System" nor in "Job" settings !

### ISSUE THREAD

**Issue by sudhir6199** [jenkinsci/service-now-plugin#17]
I installed this plugin got from https://plugins.jenkins.io/service-now in jenkins  2.190.1  plugin installed successfully and but even after restart, am unable to find servicenow option neither in "Configure System" nor in "Job" settings .

**Comment by jmcshane** [comment]
@sudhir6199 this plugin only creates bindings for Jenkins pipelines, there are no global configuration or job settings available at this time.

**Comment by sudhir6199** [comment]
@jmcshance I really didn't get purpose of this plugin or the meaning of creates binding for "Jenkins pipelines" but thankyou for your quick response for the post. Somehow for time being now I managed creating tickets adding below API in Jenkins Jobs as a script.

curl -X POST -H "Content-Type: application/json" -d '{"short_description":"Test incident creation through REST", "comments":"These are my comments"}' https://dsd93315.service-now.com/api/now/v1/table/incident --user 'username':'password'
